services:
  mysql:
    image: mysql:8.0
    container_name: kissan_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: kissan_db
      MYSQL_USER: kissan
      MYSQL_PASSWORD: kissan_secret
    ports:
      - "3306:3306"
    volumes:
      - kissan_mysql_data:/var/lib/mysql

volumes:
  kissan_mysql_data:
